name: media_view
description: Display images for all types, including a full-screen dialog, pinch & zoom.
version: 0.0.3
homepage: https://tranhuongk.xyz/

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"
  
dependencies:
  cached_network_image: 
  dismissible_page: 
  flutter:
    sdk: flutter
  flutter_svg: 
  shimmer: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  dart_code_metrics_presets: 2.6.0

flutter:
  assets: 
    - assets/
  uses-material-design: true
